//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_RV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UserID { get; set; }
        public int LoginID { get; set; }
        public string Nombre { get; set; }
        public string Genero { get; set; }
        public System.DateTime Fec_Nac { get; set; }
        public string Direccion { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
